version: "3.8"
services:
  rabbitMQ:
    container_name: rabbitmq
    image: rabbitmq:3.12
    ports:
      - "5672:5672"
    networks:
      - eCommerce
    restart: on-failure
  discovery-server:
    container_name: discovery
    build:
      context: ./discovery-server/
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    networks:
      - eCommerce
    restart: on-failure

  api-gateway:
    container_name: gateway
    build:
      context: ./api-gateway/
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - eCommerce
    restart: on-failure



networks:
  eCommerce:
    driver: bridge
