eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411
  tracing:
    sampling:
      probability: 1.0

logging:
  level:
    com:
      netflix:
        discovery:
          shared:
            resolver:
              aws:
                ConfigClusterResolver: WARN
    gateway:
      filters:
        JwtAuthFilter: INFO
    org:
      springframework:
        cloud:
          gateway:
            route:
              routedefinition-locator: INFO
    reactor:
      netty: INFO
    root: INFO

server:
  port: 8080

spring:
  application:
    name: api-gateway